junebug/api.py
junebug/tests/test_api.py

Add a health resource that just returns an okay status.

Add basic health resource

---

junebug/api.py
junebug/command_line.py
junebug/tests/test_api.py
junebug/tests/test_command_line.py
setup.py

Add a startup script that will run the api (and add it to setup.py)

add startup script

---

junebug/api.py
junebug/tests/test_api.py

Api endpoint for a deleting a channel

---

junebug/channel.py
junebug/stores.py
junebug/tests/helpers.py
junebug/tests/test_channel.py
junebug/tests/test_command_line.py
junebug/tests/test_stores.py
junebug/tests/test_workers.py
junebug/workers.py

Have the message store take in the channel id for its methods, and have it create its own sub managers.

have the store take the channel id

---

junebug/stores.py
junebug/tests/test_stores.py

Create an outbound message store that stores the link between the unique message id and the event URL.

Create outbound message store

---

junebug/stores.py
junebug/tests/test_stores.py

Add ability to store events for outbound messages in the outbound message store.

Store events

---

docs/http_api.rst

As per https://github.com/praekelt/vumi/pull/992.

Rename status event level names

---

junebug/stores.py
junebug/tests/test_stores.py
junebug/tests/test_workers.py
junebug/workers.py

Create a vumi worker that will receive status messages related to a transport.

Create status receive worker

---

junebug/plugins/nginx/plugin.py
junebug/plugins/nginx/tests/test_plugin.py

At the moment we only reload nginx on channel start.

Change nginx plugin to reload nginx on channel or plugin stop

---

junebug/channel.py
junebug/command_line.py
junebug/config.py
junebug/tests/helpers.py
junebug/tests/test_channel.py
junebug/tests/test_command_line.py
junebug/tests/test_stores.py
junebug/tests/test_workers.py
junebug/workers.py

We need to track the message rates for MO messages. This will be done in the message forwarding worker.

Store message rates for MO messages

---

junebug/logging_service.py
junebug/tests/test_logging_service.py

Create a service that will retrieve the last N logs, possibly across multiple files.

Create logging reading service

---

CONTRIBUTING.rst

From @smn on mailing list:
> Good point! There is no documented process for this and I'd be in
favour of documenting the project's expectations around contributions
& contributors. A good starting point is adding a CONTRIBUTING.md file
to the root of the repository as per
https://github.com/blog/1184-contributing-guidelines
>
> The contributing file would document when a pull-request would be
considered for merging or not. If you have any good examples of such a
contributing file then please do share.

Add contributor guidelines.

---

docs/getting-started.rst
docs/release-notes.rst

We need to add the latest features to the release notes, as well as update the link to the demo video

Documentation updates

---

docs/amqp-integration.rst
docs/http_api.rst
docs/index.rst
docs/release-notes.rst

Hi
This pull request Fixes .event instead of .events for AMQP messages.
It also updated the release notes, and expands a bit on AMQP integration.

Documentation updates.

---

.travis.yml

It will remove a step from releasing, which is useful.

Automatically deploy on branch tags.

---

docs/index.rst
docs/internal-architecture.rst

We have a good explanation of how Junebug looks from the outside, but it would help to have a description of how it looks form the inside.

Add documentation for internal architecture.

---

junebug/workers.py

Print a bit more information when HTTP calls fail.

---

docs/cli-reference.rst

https://junebug.readthedocs.io/en/latest/cli-reference.html

Add newline so reStructuredText renders correctly

---

setup.py

Update of Vumi for the logging middleware to work.

Update vumi version to 0.6.18

---

docs/http_api.rst
docs/index.rst
docs/routers.rst

Built documentation: http://junebug.readthedocs.io/en/feature-momza-829-create-documentation-for-new-endpoints/

Add documentation for routers

---

junebug/api.py
junebug/router/__init__.py
junebug/router/base.py
junebug/router/from_address.py
junebug/stores.py
junebug/tests/test_api.py
junebug/tests/test_from_address_router.py
junebug/tests/test_router.py
junebug/tests/test_stores.py

This PR is for adding in the logic required for the from address router
Relies on https://github.com/praekelt/junebug/pull/158

Fill out from address router class

---

junebug/router/from_address.py
junebug/tests/test_from_address_router.py

In https://github.com/praekelt/junebug/pull/160 we had the from address router forward outbound messages send to the destination queue to the configured channel. It does not, however, store these messages, so when it comes to routing the events for that message, we don't know where to route them.
This PR adds the storage of the outbound messages to the from address router, as well as updating the tests to better reflect how the messages are actually travelling through the system.

Store outbound messages in from address router
