junebug/api.py, junebug/channel.py, junebug/command_line.py, junebug/error.py, junebug/service.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/test_command_line.py, junebug/tests/test_service.py, setup.py
Have the junebug API run as a twisted multiservice, and add the machinery to launch transports as child services of the API.
=> Twisted parent and child services

docs/http_api.rst, junebug/api.py, junebug/tests/test_api.py
To be more RESTful, it would be nice to have collection api endpoints that look like `/channels/` instead of `/channels`.
=> Add /s for collection api endpoints

junebug/amqp.py, junebug/api.py, junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_amqp.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/test_command_line.py, junebug/tests/test_service.py, junebug/utils.py
Add the ability to send a message across a channel by posting to `/channels/channel-id/messages`. Adds the message to the correct rabbitmq queue for the specified channel-id.
=> Send a message

junebug/command_line.py, junebug/config.py, junebug/service.py, junebug/tests/helpers.py, junebug/tests/test_command_line.py, junebug/tests/test_service.py, setup.py
Currently, all config options are added from the command line. The goal of this is to be able to specify a configuration file that can also set all of these options, instead of specifying them in the command line.
=> Get config from file

junebug/api.py, junebug/channel.py, junebug/tests/test_channel.py
Currently, whenever a channel is created, it fetches its properties from redis. For some things (mainly sending messages), this isn't needed, so we should fetch properties in a more "on demand" way, caching it on the channel object.
=> Make send_message a class method

junebug/channel.py, junebug/tests/test_channel.py, junebug/tests/test_workers.py, junebug/workers.py
We need an application worker that will take MO messages and send them to the provided URL. The plan is that a separate PR will handle the starting/stopping of the worker (when channels are started/stopped).
=> add message sending application worker

junebug/tests/test_workers.py, junebug/workers.py
Currently, getting the `mo_url` from the config results in unicode. We must convert this to bytes before trying to make an http request.
=> Fix mo_url in message forwarding worker

junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py
#20 adds an application worker for `POST`ing mo messages to a url. We plan to have one application worker instance per transport instance, and create, start and stop each application worker with its corresponding transport worker.
=> Create, start and stop application workers with their transport workers

junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/utils.py
It would be cool if we could let `Channel` do its usual transport creation.
=> Don't patch transport worker creation in api tests

junebug/channel.py, junebug/tests/test_channel.py
Currently, we delete the channel data from redis, but we don't remove the channel id from the channel list.
=> Remove channel from channel list when deleting

junebug/stores.py, junebug/tests/test_stores.py
For inbound messages, we need to store the message so that we can construct a reply_to message. The message will be stored in redis with an expiry.
=> Create inbound message store

junebug/api.py, junebug/channel.py, junebug/stores.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/utils.py
This and #26 will make replying possible.
=> Supporting sending replies

junebug/api.py, junebug/command_line.py, junebug/config.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_command_line.py
For outbound (MT) messages, we should store the mapping between the event url and the message id, using the OutboundMessageStore, so that we know where to send events to.
=> Store event urls

junebug/channel.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/test_utils.py, junebug/tests/test_workers.py, junebug/tests/utils.py, junebug/utils.py, junebug/workers.py
#30 will allow us to store the per-message event urls given to the api when sending a message. This ticket is for fetching these stored event urls in `MessageForwardingWorker` when we consume an event, and sending the event to the url.
=> Send events to per-message event urls

docs/http_api.rst, junebug/command_line.py, junebug/config.py, junebug/tests/test_command_line.py
For storing event URLs, the default should be 2 days, for replies, the default should be 10 minutes. These defaults and their implications should be documented, and the defaults should be set correctly.
=> Set and document ttls

junebug/tests/test_workers.py, junebug/workers.py
At the moment, giving event urls is optional when sending a message, yet we log an error in the message forwarding worker if no event url is found.
=> Fix message forwarding worker to ignore events without event urls

junebug/api.py, junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py
At the moment we publish first and then store, which can lead to race conditions where have not yet stored the message when handling events for the outbound message.
=> Store outbound message event urls before publish outbound messages

junebug/api.py, junebug/channel.py, junebug/tests/test_api.py, junebug/tests/test_channel.py
The character limits specified on the channel config should be checked before a message is sent, and an http error should be returned if the character limit is exceeded.
=> Character limits

junebug/channel.py, junebug/command_line.py, junebug/config.py, junebug/tests/helpers.py, junebug/tests/test_channel.py, junebug/tests/test_command_line.py
The plan is to have a default list of mappings between friendly channel types, and python classes. This list can either be appended to, or replaced, via config.
=> Generic channel support

junebug/api.py, junebug/tests/test_api.py
Now that the events for messages are being stored, we can implement the message status endpoint.
=> message status endpoint

docs/http_api.rst
At the moment, status events can have multiple reasons. Multiple reasons makes sense for the request-reply pattern, since a request might fail for multiple reasons (for e.g. multiple validation failures), but for the case of events, there can only really be a single reason for an event occuring.
=> Change documented status events to only have a single reason

junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_channel.py, junebug/tests/test_utils.py, junebug/tests/test_workers.py, junebug/utils.py, junebug/workers.py
#44 adds a worker that consumes status events published by a transport. The plan is to change the worker to post received events to a `status_url` given to it via its config.
=> POST received events to status_url in channel status worker

junebug/channel.py, junebug/stores.py, junebug/tests/test_channel.py, junebug/tests/test_stores.py
A GET request to `/channels/<channel-id>` should have the latest health event from each component in it.
=> Support GET health events

junebug/api.py, junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py
We do store a list of all the channels in redis, but when junebug starts we don't start any of them. We should start all of the channels stored in redis when junebug starts up, so that they don't need to all be recreated every time the process restarts.
=> Persistent state

junebug/api.py, junebug/channel.py, junebug/command_line.py, junebug/config.py, junebug/plugin.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/test_command_line.py, junebug/tests/test_plugin.py
In https://github.com/praekelt/junebug/pull/51 we added the interface for Junebug plugins. We now need to add infrastructure to configure which plugins get started when Junebug starts, and to have all those plugins be called in the correct places.
=> Add infrastructure to use plugins

junebug/plugins/nginx/__init__.py, junebug/plugins/nginx/location.template, junebug/plugins/nginx/plugin.py, junebug/plugins/nginx/tests/test_plugin.py, junebug/plugins/nginx/vhost.template, junebug/tests/helpers.py, junebug/tests/test_utils.py, junebug/utils.py
For smaller projects using junebug, it would be helpful to have a plugin that maintains a set of nginx config files, where each file corresponds to an http-based channel and contains a virtual server configuration for that channel that routes requests to the relevant port that the channel is listening on.
=> Add an nginx junebug plugin

junebug/stores.py, junebug/tests/test_stores.py
Create a store that can get called whenever the counter should be incremented, and be able to get the current msgs/s, with configurable bucket sizes.
=> Create message rate store

docs/http_api.rst, junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py
When a GET request is sent to `/channels/<channel-id>`, the inbound and outbound message rates should be returned.
=> Add message rates to channel status

junebug/logging_service.py, junebug/tests/test_logging_service.py
Create a logging service similar to `vumi.sentry.SentryLoggerService` that logs to a file instead of sentry, using `twisted.python.logfile` to assist with logfile rotation.
=> Add logging service

junebug/channel.py, junebug/command_line.py, junebug/config.py, junebug/logging_service.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_channel.py, junebug/tests/test_command_line.py, junebug/tests/test_logging_service.py, junebug/tests/test_stores.py, setup.py
When the transport is started, we should add the logger service to it (created in https://github.com/praekelt/junebug/pull/66) so that it can capture the logs of the worker.
=> Start logger service with transport

docs/index.rst, docs/release-notes.rst
We need to add a changelog to the documentation to document what changed with each release of Junebug.
=> Create changelog in documentation

.gitignore, MANIFEST.in
Currently `pip install junebug` leaves one with:
```
$ ls /lib/python2.7/site-packages/junebug/plugins/nginx 
__init__.py  __init__.pyc  plugin.py  plugin.pyc  tests
```
=> Add MANIFEST so that we can include package data in releases.

junebug/plugins/nginx/plugin.py, junebug/plugins/nginx/tests/test_plugin.py
When the nginx plugin starts, it writes the vhosts file, but doesn't ask nginx to reload, so the vhosts file has no effect.
=> Reload nginx when the nginx plugin starts.

junebug/plugins/nginx/tests/test_plugin.py, junebug/tests/helpers.py, junebug/tests/test_utils.py, junebug/utils.py
https://github.com/praekelt/junebug/blob/develop/junebug/utils.py#L132 returns `None` for 
```
{
"type": "smpp",
"amqp_queue": "queue",
"config": {
"web_path": "/api",
"web_port": 8051,
}
}
```
Instead I have to duplicate the info as a top level key in the config:
```
{
"type": "smpp",
"amqp_queue": "queue",
"public_http": {
"enabled": true,
"web_path": "/api",
"web_port": 8051
},
"config": {
"web_path": "/api",
"web_port": 8051,
}
}
```
This seems odd?
=> web_path and web_port parameters read from wrong places in the config

docs/http_api.rst, junebug/api.py, junebug/tests/test_api.py
Channels can be reconfigured by POST-ing to the channel resource. Depending on what values are changed, a restart may be the result.
It would be nice if a simple POST resulted in a restart to deal with transports that've disconnected. Currently the only way to achieve that is to restart all of Junebug with all configured channels.
=> Allow for channel restarts.

junebug/plugins/nginx/plugin.py, junebug/plugins/nginx/tests/test_plugin.py
Channels that require a `web_path` don't need the `web_path` to have a leading `/` because the `web_path` is always considered to be relative to the root of the site. Nginx's location directives, however, do require a leading `/` since they're reading as a raw path prefix.
E.g. If `web_path` is `foo` we currently generate an Nginx config that looks like:
```
location foo { ... }
```
when we should be generating a config that looks like:
```
location /foo { ... }
```
=> Add leading / to web_paths for nginx plugin.

junebug/tests/test_workers.py, junebug/workers.py
Currently, the teardown_application method of the MessageForwardingWorker assumes that it has a redis manager, which won't be the case if the application didn't start up properly. We should add a safeguard against this.
=> Fix MessageForwardingWorker teardown

junebug/api.py, junebug/tests/test_api.py
A 301 response currently looks like:
```{"status": 301, "code": "Moved Permanently", "description": null, "result": {"errors": [{"message": "301: Moved Permanently", "type": "Moved Permanently"}]}}```
We should at minimum include the URL that we are redirecting to.
Also, we should check that the headers are also being set correctly.
=> Better handling for 301 responses

docs/installation.rst
Installing Junebug requires libssl-dev and libffi-dev to be present on Debian systems, so our install documents should mention those in the list of packages to apt-get install.
=> Add libssl-dev and libffi-dev to install instructions

.travis.yml, setup.py
The minimum twisted version that `vumi` has is `13.2.0`, which is too low, since we rely on new style classes in Junebug. We set a minimum version (`15.0`), and also run our travis tests against our minimum version.
=> Specify minimum twisted version

junebug/tests/test_workers.py, junebug/workers.py
Currently, if Junebug gets sent an event by the transport, but the `user_message_id` of the event is `null`, the event processing crashes and gets stuck. We should just log that the event doesn't have a message id, don't store it, and carry on.
=> Don't store events without user_message_id

junebug/tests/test_api.py, junebug/tests/test_validate.py, junebug/validate.py
When making a POST to change multiple fields on a channel that generates multiple errors the response does not indicate what fields caused the errors. For example when trying to set multiple fields to `null` the following response was generated:
```json
{
"status": 400,
"code": "Bad Request",
"description": "api usage error",
"result": {
"errors": [
{
"message": "None is not of type 'string'",
"type": "invalid_body"
},
{
"message": "None is not of type 'string'",
"type": "invalid_body"
}
]
}
}
```
=> API Errors don't say what key is the problem

junebug/channel.py
In vumi, the SmppTransport is actually the depreciated SmppTransceiverTransportWithOldConfig. We should change this over to the new SmppTransceiverTransport.
=> Change SmppTransport to SmppTransceiverTransport

junebug/tests/helpers.py, junebug/tests/test_workers.py, junebug/workers.py
Currently, we will wait forever for an outbound HTTP request (from us to another service) to return. We should add a configurable timeout, with a sensible default value. `treq` provides a `timeout` parameter for us to do this.
=> Add timeout for HTTP requests

junebug/api.py, junebug/channel.py, junebug/tests/helpers.py, junebug/tests/test_channel.py, junebug/tests/test_workers.py, junebug/workers.py
Auth can either be basic auth:
```mo_url: 'https://foo:bar@example.org/'```
or via token auth:
```mo_url_auth_token: 'the token to use'```
=> Allow auth on mo_url

setup.py
The description is a tuple, for some reason this is not a problem in 
py2 but in py3 it is.
=> Installing Junebug on py3 fails because of tiny setup.py bug

setup.py
Raven 6.x.x was released in February, allow it to be used.
=> allow any 6.x.x version

junebug/workers.py
This exception is killing the channel:
`RequestTransmissionFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]`
`RequestTransmissionFailed` is a wrapper exception which contains `ConnectionDone` which we are trying to trap.
=> Trap RequestTransmissionFailed

docs/conf.py, docs/getting-started.rst, docs/release-notes.rst, docs/sphinx_argparse/ext.py, requirements-docs.txt
Currently, sphinx argparse is not working with readthedocs. There are some issues and PRs on the repo, but for now it seems like development has stalled.
This PR adds an argparse module for sphinx, which implements just the minimum functionality that we need to generate our CLI documentation, and removes the requirement on sphinx argparse.
Built documentation can be viewed at http://junebug.readthedocs.io/en/feature-momza-830-fix-junebug-documentation-build/
=> Fix Junebug readthedocs documentation build

junebug/stores.py, junebug/tests/test_stores.py
The current structure won't work too well when we want to start nesting things deeper, which we want to do when we start adding the other router endpoints. This is a rework of how the router store stores configs to allow easier expansion in the future
=> Change structure for the router store

junebug/router/base.py, junebug/tests/helpers.py
The vumi base worker class already has a `validate_config` function, which gets called when the vumi worker gets started. We should rename our `validate_config` function so that there's not a clash.
Also, by default the `setup_connectors`, `setup_worker`, and `teardown_worker` functions raise a `NotImplementedError`. We should add dummy functions to the test router so that we can use the dummy router for testing.
The reason this isn't picked up in unit tests is that we don't actually start and stop the workers in the unit tests, as per https://github.com/praekelt/junebug/issues/50
=> Change function from validate_config to validate_router_config

junebug/tests/test_api.py, junebug/utils.py
Currently, if bad JSON is POSTed in the body of a request, we get an unhandled ValueError, and so a 500 server error is returned. This is not correct, as bad JSON in the body of the request is not a server error, it is a 400 bad request error, and so that should be returned instead.
This should also mean that incorrect JSON in the body won't be reported to sentry
=> Add handling for invalid json in body decoding

docs/http_api.rst
`mo_url_token` doesn't do anything, I think it should be `mo_url_auth_token`.
Not sure if this applies both to channels and routers?
=> Fix mo_url_auth_token in docs

junebug/api.py, junebug/channel.py, junebug/router/__init__.py, junebug/router/base.py, junebug/router/from_address.py, junebug/stores.py, junebug/tests/helpers.py, junebug/tests/test_api.py, junebug/tests/test_from_address_router.py, junebug/tests/test_router.py, junebug/tests/test_stores.py, junebug/tests/test_workers.py
This PR adds a base class for router workers that includes some helpful methods that should be common across most routers.
The from address router will be created in a separate PR, as to have slightly smaller PRs
=> Add a base class for router workers

junebug/router/base.py, junebug/router/from_address.py, junebug/tests/test_from_address_router.py, junebug/tests/test_router.py
Currently, the from address router doesn't handle outbound messages from destinations, and the base router worker class doesn't provide any helper functions to do so.
This PR adds both of those items.
=> Have routers handle outbound messages from destinations
